[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.regex]
target = 'card.lua'
pattern = 'repetitions \= 1,\W                    card \= self'
position = 'at'
payload = '''repetitions = self.ability.SRSreps or 1,
                    card = self'''
overwrite = true

[[patches]]
[patches.regex]
target = 'card.lua'
pattern = 'self\.seal \= _seal'
position = 'at'
payload = '''self.seal = _seal
        SRS_setRedSeal(self,_seal)
'''
overwrite = true

[[patches]]
[patches.regex]
target = 'functions/common_events.lua'
pattern = 'if v \== .red.*'
position = 'at'
payload = '''if v == 'red_seal' then
                if card.ability.SRSreps and card.ability.SRSreps > 1 then
                    info_queue[#info_queue+1] = {key = 'SRSredSeal', set = 'Other', vars = {card.ability.SRSreps}}
                else
                    info_queue[#info_queue+1] = {key = 'red_seal', set = 'Other'}
                end
            end'''

overwrite = true